language: c

dist: trusty
sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      libpcap-dev

matrix:
  include:
    - language: nix
      script: nix-build
      addons:

script: make
